# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S5

  pod 'Alamofire', '~>4.5'
  pod "SwiftyJSON", ">= 2.2"
  pod 'AudioKit'
  pod 'SwiftGifOrigin', '~> 1.6'

  target 'S5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'S5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
